{
    'name': 'Material Lab Theme',
    'description': "Material Lab Theme",
    'category': 'Themes/Corporate',
    'version': '1.0',
    'author': 'EZESELLING',
    'maintainer': 'EZESELLING',
    'depends': ['website',
                'website_crm',
                'theme_default'],
    'data': [
        'views/assets.xml',
        'views/customize_modal.xml',
        'views/layout.xml',
        'views/snippets/s_slider_material.xml',
        'views/snippets/s_feature_area.xml',
        'views/snippets/s_about_us.xml',
        'views/snippets/s_project_area.xml',
        'views/snippets/s_protfolio_area.xml',
        'views/snippets/s_whychoose.xml',
        'views/snippets/s_service_area.xml',
        'views/snippets/s_social_btn.xml',
        'views/snippets/s_our_team.xml',
        'views/snippets/s_process_area.xml',
        'views/snippets/s_skill_and_video.xml',
        'views/snippets/s_pricing_table.xml',
        'views/snippets/s_client_part.xml',
        'views/snippets/s_partner_area.xml',
        'views/snippets/s_blog_area.xml',
        'views/snippets/s_subscribe_area.xml',
        'views/snippets/s_contact.xml',
        'views/snippets/s_footer_social.xml',
        'views/snippets.xml',
    ],
    'demo': [
        'data/menu_data.xml',
        'demo/demo.xml',
    ],
    'price': 249.99,
    'currency': 'EUR',
}
